### ISSUE TITLE
Formatting request for Year?

### ISSUE THREAD

**Issue by kochbj** [ourresearch/openalex-elastic-api#1]
Hi guys,

First I just want to congratulate you on how great OpenAlex is. :) The API addresses a lot of basic use cases that were nearly impossible with the super-complicated MAG API (i.e., counting citations over time). I've been working on dpriskorn's Python API the past week and had a question about the design of the "by_year" methods.

1. Is there a reason the API doesn't include 0-count years?
2.  If 0-count years are included, would it be possible to return these as sequences?
3. Could these sequences be expanded past 10 years? It's a onetime cost to compute these sequences, and for most analyses where you might be interested in citation sequences, you will need the full sequence since citation counts do not follow uniform distributions.

Thanks,
Bernie

**Comment by caseydm** [comment]
Hi Bernie. Thanks for the awesome feedback!

You are right, we do not include years that have 0 works and 0 citations in the counts_by_year field. We removed them to save some space. I added a note to the documentation to make it clear that users will have to account for those years and add them back if they need it for their use case.

No, for now we need to stick to the 10-year limit on counts_by_year. But we will definitely consider expanding it in the future!

Casey

**Comment by kochbj** [comment]
Hi Casey,

Thanks for your responses! I'm responding now so I don't forget.

I'm a social scientist/scientist of science. Ive been using the API a lot to model citations. Citation prediction/modeling was one of the most common use cases for SoS research with MAG, and you need the full citation sequence to do it. I understand that storage is constrained for saving this information, but it's a storage-compute tradeoff; I just ended up hammering the API (as I did with MAG) to retrieve every paper that cites the ones I was interested. Anyways, this is the use-case for requesting zero-cites, array of dicts structure, 10+ years!

Since you're requesting feedback, the other thing I've noticed over the past couple weeks is that author disambiguation is currently quite conservative. I found a lot of authors who have the same affiliation, name, and concepts but were listed as separate entities. But I gather from the newsletter this is something you guys are actively tinkering with.

Best,
Bernie
